"""Agent run/step status constants (single source of truth)."""

RUN_PENDING = "PENDING"
RUN_RUNNING = "RUNNING"
RUN_WAITING_APPROVAL = "WAITING_APPROVAL"
RUN_COMPLETED = "COMPLETED"
RUN_FAILED = "FAILED"

STEP_OK = "OK"
STEP_PENDING_APPROVAL = "PENDING_APPROVAL"
STEP_FAILED = "FAILED"
STEP_SKIPPED = "SKIPPED"
